init_pose:
  alpha: -10.4  # degree
  beta: -19.6   # degree

geom:
  sdd: 943.0
  sod: 736.9425104
  height: 512
  delx: 0.368

data:
  img_path: data/3D/xu_total.nii.gz
  seg_path: data/3D/xu_total_seg_partial.nii.gz
  whole_heart_label_path: data/3D/xu_whole_heart_seg.nii.gz
  # img_path: data/3D/bianchuanbai.nii.gz
  # seg_path: data/3D/bianchuanbai_seg_partial.nii.gz
  # whole_heart_label_path: data/3D/bianchuanbai_whole_heart_seg.nii.gz
  image_2d_path: data/xu_with_aorta.png
train:
  # n_itrs: 200  # 仅当 coarse_to_fine.stages 中 没有定义 n_itrs 时才使用
  val_interval: 10

optimizer:
  type: "adam"
  lr_rotations: 0.01
  lr_translations: 3.0
  init_args: {}


# loss:
#   type: "LNCC"
#   init_args:
#     spatial_dims: 2
#     kernel_size: 71
#   multiscale: [0, 1, 2, 4, 8]

loss:
  - type: "MI"
    weight: 1.0

  - type: "SSIM"
    weight: 1.0

drr:
  resample_factor: 0.5


coarse_init:
  img_downsample_stride: 4
  init_gamma_deg: 0.0
  alpha_grid:
    window_size: 5.0
    step_size: 1.0
  beta_grid:
    window_size: 5.0
    step_size: 1.0
  sod_grid:
    window_size: 10.0
    step_size: 2.0


coarse_to_fine:
  stages:
    - name: coarse
      downsample_stride: 4
      n_itrs: 100
    - name: mid
      downsample_stride: 2
      n_itrs: 100
    - name: fine
      downsample_stride: 1
      n_itrs: 100